# Generated by Django 3.1.3 on 2022-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20220527_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('F', 'follow'), ('L', 'like'), ('R', 'Reply')], max_length=1),
        ),
    ]
