# Generated by Django 3.1.3 on 2022-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220517_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='header',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
