# Generated by Django 3.1.3 on 2022-06-03 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraccount_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
