# Generated by Django 3.1.3 on 2022-06-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220603_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_name',
            new_name='profile_name',
        ),
    ]
