# Generated by Django 3.1.3 on 2022-05-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_follower_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following_list',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
