export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_FAIL = "LOAD_COMMENTS_FAIL";
export const SET_COMMENTS_SUCCESS = "SET_COMMENTS_SUCCESS";
export const SET_COMMENTS_FAIL = "SET_COMMENTS_FAIL";

export const SET_USER_DETAIL_SUCCESS = "SET_USER_DETAIL_SUCCESS";
export const SET_USER_DETAIL_FAIL = "SET_USER_DETAIL_FAIL";

export const LOAD_MENU_SUCCESS = "LOAD_MENU_SUCCESS";
export const LOAD_MENU_FAIL = "LOAD_MENU_FAIL";

export const LOAD_BOOKMARK_SUCCESS = "LOAD_BOOKMARK_SUCCESS";
export const LOAD_BOOKMARK_FAIL = "LOAD_BOOKMARK_FAIL";

export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_FAIL = "BOOKMARK_FAIL";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_CONFIRM_SUCCESS = "RESET_PASSWORD_CONFIRM_SUCCESS";
export const RESET_PASSWORD_CONFIRM_FAIL = "RESET_PASSWORD_CONFIRM_FAIL";

export const SET_EMAIL_SUCCESS = "SET_EMAIL_SUCCESS";
export const SET_EMAIL_FAIL = "SET_EMAIL_FAIL";

export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL";

export const LOGOUT = "LOGOUT";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const RESET_STATE = "RESET_STATE";
////
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_FAIL = "LOAD_POSTS_FAIL";
export const LOAD_USER_POSTS_SUCCESS = "LOAD_USER_POSTS_SUCCESS";
export const LOAD_USER_POSTS_FAIL = "LOAD_USER_POSTS_FAIL";
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS";
export const LOAD_POST_FAIL = "LOAD_POST_FAIL";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAIL = "LIKE_FAIL";
export const LOAD_LIKE_SUCCESS = "LOAD_LIKE_SUCCESS";
export const LOAD_LIKE_FAIL = "LOAD_LIKE_FAIL";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL";

export const LOAD_MSG_SUCCESS = "LOAD_MSG_SUCCESS";
export const LOAD_MSG_FAIL = "LOAD_MSG_FAIL";

export const LOAD_ROOMS_SUCCESS = "LOAD_ROOMS_SUCCESS";
export const LOAD_ROOMS_FAIL = "LOAD_ROOMS_FAIL";

export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAIL = "FOLLOW_FAIL";
